theme: jekyll-theme-slate
show_downloads: true
github:
  zip_url: https://git.x4m3.rocks/vim-dhex/snapshot/vim-dhex-master.zip
  tar_url: https://git.x4m3.rocks/vim-dhex/snapshot/vim-dhex-master.tar.xz
